
- name: ----------DEPLOYMENT----------
  hosts: web_server

  roles:
    - java
    - tomcat
    - nginx
    - java_test
    - tomcat_test
    - nginx_test
    - deploy_war


- name: ----------DEPLOY WEBAPP----------
  hosts: localhost
  tasks:
  - name: calling sh
    deploy: url=192.168.33.10 war=mnt-lab.war user=vagrant password=vagrant

- name: ----------INFO UPDATING----------
  hosts: web_server
  become: yes

  tasks:
  - name: Creating and updating
    shell: |
     mkdir -p /var/lib/tomcat/webapps
     cat /opt/tomcat/current/logs/catalina.out | grep mnt-lab | tail -1 | awk '{print  $2}' > /var/lib/tomcat/webapps/deploy-info.txt
     echo -e `awk -v val=501 -F ":" '$3==val{print $1}' /etc/passwd ` >> /var/lib/tomcat/webapps/deploy-info.txt

